### ISSUE TITLE
Novas políticas do hacktoberfest

### ISSUE THREAD

**Issue by Gabrielr2508** [vuejs-br/docs-next#147]
Pessoal, devido a quantidade de spams que está rolando nesse hacktoberfest o pessoal da DO atualizou as regras. A partir de agora a participação dos repositórios no programa é opcional.

Caso seja interesse dos mantenedores desse projeto participar da celebração, precisa-se adicionar o tópico hacktoberfest ao repositório.

Segue o link do comunicado: https://hacktoberfest.digitalocean.com/hacktoberfest-update

Valeu!

**Comment by GuiDevloper** [comment]
Tópico adicionado.
Agradeço mesmo pelo aviso, @Gabrielr2508, eu não sei quando saberia se não fosse tua _issue_.
