### ISSUE TITLE
Traduzir "guide/component-provide-inject.md"

### ISSUE THREAD

**Issue by ErickPetru** [vuejs-br/docs-next#16]

**Comment by dumedeiros** [comment]
Olá, @ErickPetru!

Vou iniciar a tradução deste arquivo!

**Comment by ErickPetru** [comment]
@GuiDevloper @arthurbergmz e @gabemule queremos ouvir a opinião de vocês sobre este assunto:

Traduzir o título da seção "Provide / Inject" para "Prover / Injetar" ou para "Injeção de Dados"... Eu sou mais a favor da segunda opção, por mais que a palavra "prover" suma, acredito que tem muito mais a ver com o assunto e pode facilitar falantes de português com pouca afinidade com inglês a saberem do que se trata antes mesmo de abrir o link. O que acham?

**Comment by GuiDevloper** [comment]
Opa @ErickPetru, polêmica interessante aí.

De cara tua segunda opção já leu e soou melhor.
Fui ler pra pegar mais contexto e realmente a dupla tem uma importância conjunta, então de forma à manter descritivo e conservativo do conceito original pensei que poderíamos usar algo como "Prover e Injetar Dados".
Pai providencia e filho injeta o dado.

PS: Também fiquei curioso e apreensivo pro desfecho dessa [polêmica do `myObject`](https://github.com/vuejs-br/docs-next/pull/37#issuecomment-699656811).

**Comment by ErickPetru** [comment]
Legal @GuiDevloper, ideia simples mas muito coerente, não sei como não pensei antes. A gente elimina a `/` que é super inelegivel e ainda esclarece que estamos falando de passagem de dados, não de injeção de dependências tradicional de outras linguagens/frameworks.

Se ninguém votar contra, vamos de "**Prover e Injetar Dados**".
