### ISSUE TITLE
Traduzir "guide/instance.md"

### ISSUE THREAD

**Issue by GuiDevloper** [vuejs-br/docs-next#170]
Link para o arquivo: [guide/instance.md](https://github.com/vuejs-br/docs-next/blob/master/src/guide/instance.md)

Anteriormente traduzido em #3 por @dumedeiros.
O time oficial fez uma reescrita braba [aqui](https://github.com/vuejs/docs-next/pull/514) e mesmo tentando manter algo em português o arquivo mudou muito.

**Comment by andrewlucasgs** [comment]
Olá. Gostaria trabalhar nessa issue.

**Comment by GuiDevloper** [comment]
Então vai que é tua, @andrewlucasgs.
