### ISSUE TITLE
Hacktoberfest Label

### ISSUE THREAD

**Issue by Gabrielr2508** [vuejs-br/docs-next#182]
Pessoal, como mencionei na issue #147 as novas politicas do hacktoberfest precisam que o repositório tenha a tag `hacktoberfest`. (Isso foi resolvido 😄)

Mas há outro detalhe. Acontece que para que a PR conte como uma contribuição válida ela precisa atender um dos seguintes casos:

```
PRs count if:
Submitted during the month of October AND
Submitted in a public repo AND (
  The PR is labelled as hacktoberfest-accepted by a maintainer OR
  Submitted in a repo with the hacktoberfest topic AND (
    The PR is merged OR
    The PR has been approved
  )
)
```

A minha sugestão é que PRs que entrem no estado de revisão recebam a label ` hacktoberfest-accepted`, pois o processo de revisão depende da disponibilidade dos mantenedores e o prazo de review de 15 dias do hacktoberfest passa a contar a partir do aceite da PR, ou seja, caso a revisão demore os participantes do evento teriam procurar outros repositórios para contribuir.

O que acham? Alguma outra sugestão?

https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by GuiDevloper** [comment]
Opa @Gabrielr2508.
Primeiramente, legal que esteja atento à detalhes para o bem da comunidade!

Pesquisei, tive ideias e finalmente fiz um teste para ter certeza (PR #192)
Então, toda PR enviada em Outubro é válida.
E o período de review é sobre eles verificarem se a PR mesclada não teve _rollback_ e não recebeu tag `invalid`.

Ao que tudo indica dá pra correr toda revisão no tempo normal de jogo e tudo está válido.
No final, o maior prêmio dessas contribuições é ter a honra de se reunir com tanta gente se engajando e sendo eternizadas :)

E que tudo dê certo!
Nem que eu aponte agradecendo um por um em alguma publicação oficial histórica :sweat_smile:

**Comment by viniciusarre** [comment]
Opa, @Gabrielr2508, gostaria de adicionar alguns detalhes complementando esta issue... Pelo meu entendimento, a partir deste ano, não basta esperar um tempo até que o PR não receba a tag de invalid para que ele seja validado. Lembro-me que no ano passado este período de review era de quatro dias, por exemplo. Atualmente, as minhas contribuições estão pendentes, como aponta a foto abaixo

![image](https://user-images.githubusercontent.com/20468645/97287716-ac62a500-1823-11eb-9cb9-99727da352e3.png)

Para que isso se resolva, é necessário fazer isso:

![image](https://user-images.githubusercontent.com/20468645/97287930-ee8be680-1823-11eb-937b-d7637594c04c.png)

Se você puder adicionar a label `hacktoberfest-accepted` aos PRs ou aprová-los, nos ajudaria muito!

Espero ter ajudado... obrigado por ter lido!

**Comment by teffybiskup** [comment]
Faço das palavras do @viniciusarre as minhas!

**Comment by GuiDevloper** [comment]
Olá pessoal.

Complementando o que eu disse, pra mim a mais válida e valiosa é a contribuíção tendo aprovação com aquele review.

Até por aparecerem PRs curiosas e outras com problemas rotineiros normais, como _commit_ errado, que podem acabar fechadas (valeria ter aprovado antecipadamente?)

Nisso de buscar revisar tudo pra qualidade e melhor validade da contribuição, já revisei (como nunca imaginei) 43 PRs.

E tô aqui pra não parar, disse que poderia fazer um post homenageando todo mundo, mas se no final não contabilizarem alguém, entrego "meu prêmio" disso aí pra quem precisar.

Quem realmente precisar de antecipação pode me marcar aí que coloco as tags.
Valeu pelo trabalho doido que tens feito!

**Comment by teffybiskup** [comment]
Acredito se tratar mais de um medo pelo fim do mês estar se aproximando, e no meu caso eu apenas fiz contribuições aqui, então não tenho 4 approvals no Hacktoberfest ainda 😅 Eu imagino a exaustão que está sendo para vocês, e gostaria de dizer parabéns ao bom trabalho!

**Comment by GuiDevloper** [comment]
Deu vontade de apostar uns cafés com o @viniciusarre de que podia ficar tranquilo que as contribuições já estão feitas :sweat_smile:

Enfim aqui estamos, confirmem aí o `In Review` na DigitalOcean e.. comemoramos?
Boas próximas contribuições pra vocês :)

**Comment by teffybiskup** [comment]
_"Congratulations on submitting 4 PRs during Hacktoberfest!"_
Tudo certo por aqui! Muito obrigada 😊

**Comment by Gabrielr2508** [comment]
Gente, acho que as dúvidas foram esclarecidas. :)  Tô fechando a issue, se acharem necessário, podem abrir novamente.
