### ISSUE TITLE
Traduzir partes adicionadas após atualização com upstream

### ISSUE THREAD

**Issue by GuiDevloper** [vuejs-br/docs-next#228]
## Partes necessitando tradução/revisão:

- [x] #250
- [x] #255
- [x] #268
- [x] #269
- [x] #264
- [x] #270
- [x] #254
- [x] #271
- [x] #272
- [x] #265
- [x] #253
- [x] #251
- [x] #252
- [x] #237
- [x] #238
- [x] #273
- [x] #248
- [x] #274
- [x] #275
- [x] #277
- [x] #278
- [x] #229
- [x] #279
- [x] #266
- [x] #249
- [x] #282
- [x] #285
- [x] #284
- [x] #286

## Instruções

- Verifique qual da lista poderá contribuir (pelo arquivo e _commit_ de mudanças)
- Comente o número/arquivo e prossiga com o processo comum de contribuição (_fork_/mudança/PR)
- Referencie o mesmo número e esta _issue_ na sua PR

**Comment by GuiDevloper** [comment]
#### Exemplo de contribuição

Vou contribuir fazendo o 22, jaja mando PR!

**Comment by viniciusdeliz** [comment]
Will do item 5
