### ISSUE TITLE
Exemplo do modal não funciona

### ISSUE THREAD

**Issue by schneider8357** [vuejs-br/docs-next#294]
A documentação do componente modal (<https://vuejsbr-docs-next.netlify.app/examples/modal.html>) não está funcionando.

O erro apresentado no codepen é este:
```
ReferenceError: Vue is not defined 
 at https://cdpn.io/cpe/boomboom/pen.js?key=pen.js-38c73b13-aeec-4949-40fa-3a20096873fe:1
 ```

![image](https://github.com/vuejs-br/docs-next/assets/40526466/31b6cb4e-5466-4c7a-9932-812c84c16bdb)

**Comment by viniciusdeliz** [comment]
O problema é que o pacote `@vue/next` que o exemplo do CodePen referencia não funciona mais.
Neste momento, ao navegar para a url do pacote, https://unpkg.com/vue@nuxt, nenhum arquivo é retornado:
<img width="246" alt="vue-next-unpkg" src="https://github.com/vuejs-br/docs-next/assets/5748616/aa4690b1-1f6e-4fff-9bbd-5d1fd7c5db14">
Se você apertar para editar o exemplo codepen, e nas configurações do exemplo codepen mudar a URL do pacote JS para https://unpkg.com/vue, o exemplo vai funcionar normalmente. Você pode usar esse exemplo que eu fiz agora usando outra CDN para testar: https://codepen.io/deliz/pen/vYPzJXK

---

Dito isto, preciso dizer que o link do exemplo `Modal` da atual documentação do Vue em Português é esse: https://pt.vuejs.org/examples/#modal. Este exemplo funciona perfeitamente, como esperado.

Não são mais utilizados arquivos _snippets_ CodePen para mostrar os exemplos em Vue. Agora salve engano Vue usa [CodeMirror](https://codemirror.net/) embutido nas dependências. 

A versão atualizada da documentação em inglês deste exemplo está neste link: https://vuejs.org/examples/#modal.

A versão deste repositório corrente em Português segue uma versão antiga da documentação. Apesar de estar toda traduzida e quase plenamente funcional (vejo que nenhum dos exemplos funciona, infelizmente), esta não é a versão mais atualizada. A versão em Português em vigor agora é a do seguinte link: https://pt.vuejs.org/

**Comment by schneider8357** [comment]
Muito obrigado, não tenho ideia de como cheguei a esse link do netlify. A doc oficial funciona bem mesmo, valeu!
