### ISSUE TITLE
Automatization commands runner

### ISSUE THREAD

**Issue by GuiDevloper** [vuejs-br/docs-next#47]
Atenção quem estiver sendo notificado (e.g. por criação de _issues_) pois execução em massa pode lotar e-mail.
@ErickPetru

**Comment by ErickPetru** [comment]
Valeu @GuiDevloper, por segurança tirei o watch do repo.

**Comment by GuiDevloper** [comment]
Se tudo instalado, vou começar num simples pra ver o que acontece.
/CriaIssues support-vuejs

**Comment by GuiDevloper** [comment]
Testemunha aí, @ErickPetru.

Mais um experimento indo pro mundo, evoluem tão rápido.. :sweat_smile:
Agora bot, hora de dormir (Só faltava responder "Boa noite, papai" haha)

**Comment by ErickPetru** [comment]
Estou estarrecido com esta maravilha @GuiDevloper!
Pena que agora estamos com quase 100 issues abertas. Hora dos colaboradores trabalharem ainda mais. 😅
